{% set name = "qiskit-dynamics" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-dynamics-{{ version }}.tar.gz
  sha256: 5785e230d7bdbc6d573062290d6073a75ccec93b26c4889bb66be4dcc74ef6ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install .[jax] -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy >=1.17
    - scipy >=1.4
    - matplotlib-base >=3.0
    - qiskit
    - multiset >=3.0.1
    - sympy >=1.12
    - arraylias
    - jax >=0.4.0,<=0.4.6
    - jaxlib >=0.4.0,<=0.4.6


test:
  imports:
    - qiskit_dynamics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-dynamics
  summary: Qiskit ODE solver
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bastianzim
    - wshanks
