{% set name = "qiskit-dynamics" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-dynamics-{{ version }}.tar.gz
  sha256: 5eb5199d26254cd8637bf274206d96179adac9c9dfa8018a8aecc1ec9db0a823

build:
  noarch: python
  script: {{ PYTHON }} -m pip install .[jax] -vv
  number: 1

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy >=1.17
    - scipy >=1.4
    - matplotlib-base >=3.0
    - qiskit
    - multiset >=3.0.1
    - sympy >=1.12
    - arraylias
    - jax
    - jaxlib


test:
  imports:
    - qiskit_dynamics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-dynamics
  summary: Qiskit ODE solver
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bastianzim
    - wshanks
