{% set name = "qiskit-dynamics" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ceef3118a7756d326998f635de4d347fb9d9a9b33e1178cd172a3baff203a3ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install .[jax] -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.17
    - scipy >=1.4
    - matplotlib-base >=3.0
    - qiskit <=1.3
    - multiset >=3.0.1
    - sympy >=1.12
    - arraylias
    - jax
    - jaxlib


test:
  imports:
    - qiskit_dynamics
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/qiskit-community/qiskit-dynamics
  summary: Qiskit ODE solver
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bastianzim
    - wshanks
